---
apiVersion: v1
kind: Namespace
metadata:
  name: game-204873
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-204873
  name: deployment-204890
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-204892
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-204892
    spec:
      containers:
      - image: 254375088528.dkr.ecr.us-east-1.amazonaws.com/idv
        imagePullPolicy: Always
        name: app-204892
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-204873
  name: service-204891
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"  
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-204892
---
